services:
  - type: web
    name: fastapi-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: POSTGRES_SERVER
        fromDatabase:
          name: fastapi-db
          property: host
      - key: POSTGRES_USER
        fromDatabase:
          name: fastapi-db
          property: user
      - key: POSTGRES_PASSWORD
        fromDatabase:
          name: fastapi-db
          property: password
      - key: POSTGRES_DB
        fromDatabase:
          name: fastapi-db
          property: database

databases:
  - name: fastapi-db
    databaseName: fastapi_db
    user: fastapi_user
    plan: free 